version: "3.9"

services:
  service1:
    build:
      context: ./services/search
      dockerfile: Dockerfile
    container_name: search
    ports:
      - "8050:8050"
    restart: always

  service2:
    build:
      context: ./services/recommendation
      dockerfile: Dockerfile
    container_name: recommendation
    ports:
      - "8051:8051"
    restart: always

  service3:
    build:
      context: ./services/payment
      dockerfile: Dockerfile
    container_name: payment
    ports:
      - "8052:8052"
    restart: always

  service4:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - "8053:8053"
    restart: always
